name: map_pgan
output_type: voxel
num_views: 7
in_channels: 1
feature_dim: 64
pos_enc_dim: 60
geometry:
  camera_distance: 200.0
  detector_size: [256, 256]
  global_voxel_shape: [256, 256, 256]
map_pgan:
  base_channels: 16
  latent_channels: 64
  internal_shape: [48, 50, 26]
  use_gan: false
  lambda_adv: 0.0
