name: stomp_fem
output_type: voxel
num_views: 7
fem:
  shared_dir: /home/foods/pro/FMT-SimGen/output/shared_mesh_20k
stomp_fem:
  num_iters: 20
  max_support: 128
  threshold_sigma: 2.5
  normalize_measurement: true
  nonnegative: true
  mesh_to_voxel: barycentric
  n_candidates: 32
