#!/usr/bin/env python3
"""
Collect dispersed summary files from the entire repo and centralize to docs/summaries/.
Also updates docs/summaries/INDEX.md.
"""

import re
from pathlib import Path
from typing import List, Tuple


def find_summary_files(root: Path = Path(".")) -> List[Path]:
    """Find files that match summary/report/notes patterns."""
    patterns = [
        r".*summary.*\.md$",
        r".*总结.*\.md$",
        r".*notes.*\.md$",
        r".*report.*\.md$",
    ]
    
    summary_files = []
    for pattern in patterns:
        for file in root.rglob("*.md"):
            # Skip files already in docs/summaries/
            if "docs/summaries" in str(file):
                continue
            # Skip docs/README, docs/migration
            if "docs/" in str(file) and "summaries" not in str(file):
                continue
            
            if re.match(pattern, file.name, re.IGNORECASE):
                summary_files.append(file)
    
    return list(set(summary_files))  # Remove duplicates


def move_file(src: Path, dest_dir: Path) -> Tuple[Path, bool]:
    """Move file to dest_dir, handling name conflicts."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / src.name
    
    # Handle name conflicts
    counter = 1
    original_stem = src.stem
    while dest.exists():
        new_name = f"{original_stem}_{counter}.md"
        dest = dest_dir / new_name
        counter += 1
    
    src.rename(dest)
    return dest, True


def update_index(summaries_dir: Path, moved_files: List[Tuple[Path, Path]]) -> None:
    """Update docs/summaries/INDEX.md with new files."""
    index_path = summaries_dir / "INDEX.md"
    
    # Read existing index
    existing_content = index_path.read_text() if index_path.exists() else ""
    
    # Build index content
    lines = [
        "# Summaries Index\n",
        "**Auto-generated by `scripts/collect_summaries.py`**\n",
        "\n",
        "## Contents\n",
        "\n",
    ]
    
    if moved_files:
        for src, dest in moved_files:
            rel_path = dest.relative_to(Path("."))
            lines.append(f"- [{dest.name}]({rel_path})\n")
    else:
        lines.append("(None yet - run the collection script to populate)\n")
    
    index_path.write_text("".join(lines))
    print(f"✓ Updated {index_path}")


def main():
    """Main function."""
    root = Path(".")
    summaries_dir = root / "docs" / "summaries"
    
    # Find summary files
    summary_files = find_summary_files(root)
    
    if not summary_files:
        print("No summary files found.")
        return
    
    print(f"Found {len(summary_files)} summary file(s):")
    for f in summary_files:
        print(f"  - {f}")
    
    # Move files
    moved_files = []
    for src in summary_files:
        dest, success = move_file(src, summaries_dir)
        if success:
            moved_files.append((src, dest))
            print(f"✓ Moved {src} → {dest}")
    
    # Update index
    if moved_files:
        update_index(summaries_dir, moved_files)
        print(f"\n✓ Collected {len(moved_files)} file(s) to {summaries_dir}")


if __name__ == "__main__":
    main()
